//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardTemperature
    {
        public int Id { get; set; }
        public int IdBoard { get; set; }
        public double TemperatureValue { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Board Board { get; set; }
    }
}
